/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTasksRouteImport } from './routes/demo.tasks'
import { Route as DemoAiRouteImport } from './routes/demo.ai'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTasksRoute = DemoTasksRouteImport.update({
  id: '/demo/tasks',
  path: '/demo/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiRoute = DemoAiRouteImport.update({
  id: '/demo/ai',
  path: '/demo/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/demo/ai': typeof DemoAiRoute
  '/demo/tasks': typeof DemoTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/demo/ai': typeof DemoAiRoute
  '/demo/tasks': typeof DemoTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/demo/ai': typeof DemoAiRoute
  '/demo/tasks': typeof DemoTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/chat' | '/demo/ai' | '/demo/tasks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/chat' | '/demo/ai' | '/demo/tasks'
  id: '__root__' | '/' | '/api/chat' | '/demo/ai' | '/demo/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  DemoAiRoute: typeof DemoAiRoute
  DemoTasksRoute: typeof DemoTasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tasks': {
      id: '/demo/tasks'
      path: '/demo/tasks'
      fullPath: '/demo/tasks'
      preLoaderRoute: typeof DemoTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai': {
      id: '/demo/ai'
      path: '/demo/ai'
      fullPath: '/demo/ai'
      preLoaderRoute: typeof DemoAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  DemoAiRoute: DemoAiRoute,
  DemoTasksRoute: DemoTasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
